OnlineStrategyGame/OnlineStrategyGame.WebApp/Controllers/RaceCreatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineStrategyGame.Base.RaceCreator.Interfaces;
using OnlineStrategyGame.Base.Security;
using OnlineStrategyGame.Database.MSSQL.Models;
using OnlineStrategyGame.Dtos.RaceCreator;
using OnlineStrategyGame.WebApp.Controllers.Base;
using OnlineStrategyGame.WebApp.Models;
using OnlineStrategyGame.WebApp.Routing;

namespace OnlineStrategyGame.WebApp.Controllers
{
    [Authorize(Policy = "NewPlayerOnly")]
    [MiddlewareFilter(typeof(LocalizationPipeline))]
    public class RaceCreatorController : BaseController
    {
        private readonly IRaceCreatorManager _raceCreatorManager;
        private readonly UserManager<AppIdentityUser> _userManager;
        private readonly SignInManager<AppIdentityUser> _signInManager;

        public RaceCreatorController(UserManager<AppIdentityUser> userManager,
            IRaceCreatorManager raceCreatorManager,
            SignInManager<AppIdentityUser> signInManager)
        {
            _userManager = userManager;
            _raceCreatorManager = raceCreatorManager;
            _signInManager = signInManager;

        }
        // GET: RaceCreator
        public async Task<IActionResult> Index()
        {
            var elements = _raceCreatorManager.GetElements();
            var result = new RaceCreatorViewModel();
            result.Elements.AddRange(elements);
            //
            return View(result);
        }
        public async Task<IActionResult> Select()
        {
            return await Index();
        }

        [HttpPost]
        public async Task<IActionResult> Select(int id, int[] selected)
        {
            var elements = _raceCreatorManager.GetElements(id);
            var result = new RaceCreatorViewModel();
            result.SelectedIds.Add(id);
            result.SelectedIds.AddRange(selected);
            foreach (var item in result.SelectedIds)
            {
                result.Selected.Add(_raceCreatorManager.GetElement(item));

            }
            result.Selected.Sort(delegate (RaceCreatorElementDto x, RaceCreatorElementDto y)
            {
                return x.Id.CompareTo(y.Id);
            });
            result.Bonuses = _raceCreatorManager.GetSummaryBonuses(result.Selected);
            if (elements == null)
                return View(nameof(End), result);
            result.Elements.AddRange(elements);
            return View(nameof(Index), result);
        }

        public async Task<IActionResult> End(int[] selected)
        {
            return View(selected);
        }
        public async Task<IActionResult> Save(int[] ids)
        {
            var user = await _userManager.GetUserAsync(User);
            await _userManager.RemoveClaimAsync(user, ClaimStaticManager.GetNewPlayerClaim());
            await _userManager.AddClaimAsync(user, ClaimStaticManager.GetActivePlayerClaim());
            await _signInManager.RefreshSignInAsync(user);
            _raceCreatorManager.Save(ids, user.Id);
            return RedirectToAction("Index","Home");
        }
    }
}

OnlineStrategyGame/OnlineStrategyGame.WebApp/Controllers/SolarSystemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStrategyGame.Base.Galaxy;
using OnlineStrategyGame.Base.Galaxy.Interfaces;
using OnlineStrategyGame.Database.MSSQL;
using OnlineStrategyGame.Database.MSSQL.Models;
using OnlineStrategyGame.Dtos.Galaxy;
using OnlineStrategyGame.WebApp.Controllers.Base;

namespace OnlineStrategyGame.WebApp.Controllers
{
    [Authorize(Policy = "ActivePlayerOnly")]
    public class SolarSystemsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly ISolarSystemManager _solarSystemManager;

        public SolarSystemsController(ApplicationDbContext context, ISolarSystemManager solarSystemManager)
        {
            _context = context;
            _solarSystemManager = solarSystemManager;
        }

        // GET: SolarSystems
        public async Task<IActionResult> Index()
        {
            return View(_solarSystemManager.GetSolarSystem(1, 1, 1));
        }

        [HttpPost]
        public async Task<IActionResult> GetSolarSystem(int x, int y, int z)
        {
            var model =  _solarSystemManager.GetSolarSystem(x, y, z);
            return View("Index",model);
        }
    }
}

OnlineStrategyGame/OnlineStrategyGame.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStrategyGame.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineStrategyGame.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Lang
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Home" asp-action="SetLanguage" asp-route-lang="pl">pl</a>
                                <a class="dropdown-item" asp-controller="Home" asp-action="SetLanguage" asp-route-lang="en">en</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="RaceCreator" asp-action="Index">Race creator</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="SolarSystems" asp-action="Index">Solar system</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - OnlineStrategyGame.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>