OnlineStrategyGame/OnlineStrategyGame.WebApp/Controllers/PlanetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStrategyGame.Base.Galaxy;
using OnlineStrategyGame.Base.Galaxy.Interfaces;
using OnlineStrategyGame.Database.MSSQL;
using OnlineStrategyGame.Database.MSSQL.Models;
using OnlineStrategyGame.Dtos.Galaxy;
using OnlineStrategyGame.WebApp.Controllers.Base;

namespace OnlineStrategyGame.WebApp.Controllers
{
    [Authorize(Policy = "ActivePlayerOnly")]
    public class PlanetController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly IPlanetManager _planetManager;

        public PlanetController(ApplicationDbContext context, IPlanetManager planetManager)
        {
            _context = context;
            _planetManager = planetManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            return View(_planetManager.GetPlanet(id));
        }

    }
}

OnlineStrategyGame/OnlineStrategyGame.WebApp/Controllers/SolarSystemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OnlineStrategyGame.Base.Galaxy;
using OnlineStrategyGame.Base.Galaxy.Interfaces;
using OnlineStrategyGame.Database.MSSQL;
using OnlineStrategyGame.Database.MSSQL.Models;
using OnlineStrategyGame.Dtos.Galaxy;
using OnlineStrategyGame.WebApp.Controllers.Base;

namespace OnlineStrategyGame.WebApp.Controllers
{
    [Authorize(Policy = "ActivePlayerOnly")]
    public class SolarSystemsController : BaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly ISolarSystemManager _solarSystemManager;

        public SolarSystemsController(ApplicationDbContext context, ISolarSystemManager solarSystemManager)
        {
            _context = context;
            _solarSystemManager = solarSystemManager;
        }

        // GET: SolarSystems
        public async Task<IActionResult> Index()
        {
            return View(_solarSystemManager.GetSolarSystem(1, 1, 1));
        }

        [HttpPost]
        public async Task<IActionResult> GetSolarSystem(int x, int y, int z)
        {
            var model =  _solarSystemManager.GetSolarSystem(x, y, z);
            return View("Index",model);
        }
    }
}

OnlineStrategyGame/OnlineStrategyGame.WebApp/Views/SolarSystems/Index.cshtml
@using OnlineStrategyGame.Localisation
@model OnlineStrategyGame.Dtos.Galaxy.SolarSystemDto

@{
    ViewData["Title"] = "SolarSystemsView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>SolarSystemView</h1>

<div class="container">
    <div class="row">
        <div class="col-12">
            <form asp-controller="SolarSystems" asp-action="GetSolarSystem" method="post" class="form-horizontal">
                X: <input type="number" name="x" />
                Y: <input type="number" name="y" />
                Z: <input type="number" name="z" />
                <button type="submit" class="btn btn-primary" name="provider" value="Select" title="Select">@Localisation.Main_Go</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @Localisation.Galaxy_Star
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <tbody>
                    <tr>
                        <td>
                            @Localisation.Galaxy_Star_Mass
                        </td>
                        <td>
                            @Model.Star.Mass
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Localisation.Galaxy_Star_Radius
                        </td>
                        <td>
                            @Model.Star.Radius
                        </td>
                    </tr>
                    <tr>
                        <td>
                            @Localisation.Galaxy_Star_Temperature
                        </td>
                        <td>
                            @Model.Star.Temperature
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            @Localisation.Galaxy_Planets
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <td>
                            @Localisation.Galaxy_Planet
                        </td>
                        <td>
                            @Localisation.Galaxy_Planet_DistanceToStar
                        </td>
                        <td>

                        </td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Planets)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.DistanceToStar
                            </td>
                            <td>
                                <a asp-controller="Planet" asp-action="Index" asp-route-id="@item.Id">@Localisation.Main_Go</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

</div>